server:
  port: 8888

spring:
  profiles:
    active: vault, git
  cloud:
    config:
      server:
        vault:
          order: 1
        git:
          order: 2
          uri: https://github.com/steve-perkins/spring-config-properties
          basedir: target/config
